### ISSUE TITLE
Vérification des outputs ios

### ISSUE THREAD

**Issue by jvigne** [faberNovel/ad_localize#5]
L'output généré n'est parfois pas compilable. L'idée serait d'ajouter une étape de vérification des outputs dans le process.

Il existe une commande iOS :
`plutil -lint $(path_to_localizable.string)`

Il faudrait voir s'il existe une commande similaire sur Android

**Comment by Loruki** [comment]
I created a file to test it. It happens when there are " in the files : 
https://docs.google.com/spreadsheets/d/1vwjjunF5pgOgSAwnbBDInz5M12wgoSflZ6J_WBbmBcs/edit#gid=0

**Comment by jvigne** [comment]
Initial problem solved without adding the verification step. I close this ticket
